<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GEF1JEF" failures="8" tests="101" name="Test" time="0.202" errors="0" timestamp="2023-11-17T20:57:01 EST">
  <testcase classname="LearnTestNG.TestSenario8" name="eigth_testcase" time="0.005"/>
  <testcase classname="LearnTestNG.TestSenario8" name="fifth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario8" name="first_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario8" name="forth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario8" name="ninth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario8" name="second_testcase" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario8.second_testcase(TestSenario8.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="LearnTestNG.TestSenario8" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario8" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario8" name="tenth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario8" name="third_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario8.third_testcase(TestSenario8.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="FirstPKG.TestNGDemo" name="math1" time="0.002"/>
  <testcase classname="LearnTestNG.TestSenario9" name="eigth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario9" name="fifth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario9" name="first_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario9" name="forth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario9" name="ninth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario9" name="second_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario9" name="seventh_testcase" time="0.002"/>
  <testcase classname="LearnTestNG.TestSenario9" name="sixth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario9" name="tenth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario9" name="third_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario4" name="eigth_testcase" time="0.002"/>
  <testcase classname="LearnTestNG.TestSenario4" name="fifth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario4" name="first_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario4" name="forth_testcase" time="0.005"/>
  <testcase classname="LearnTestNG.TestSenario4" name="ninth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario4" name="second_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario4" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario4" name="sixth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario4" name="tenth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario4" name="third_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario5" name="eigth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario5" name="fifth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario5" name="first_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario5" name="forth_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario5.forth_testcase(TestSenario5.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="LearnTestNG.TestSenario5" name="ninth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario5" name="second_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario5.second_testcase(TestSenario5.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="LearnTestNG.TestSenario5" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario5" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario5" name="tenth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario5" name="third_testcase" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario5.third_testcase(TestSenario5.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="LearnTestNG.TestSenario6" name="eigth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario6" name="fifth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario6" name="first_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario6.first_testcase(TestSenario6.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="LearnTestNG.TestSenario6" name="forth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario6" name="ninth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario6" name="second_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario6" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario6" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario6" name="tenth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario6" name="third_testcase" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario6.third_testcase(TestSenario6.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="LearnTestNG.TestSenario7" name="eigth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario7" name="fifth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario7" name="first_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario7" name="forth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario7" name="ninth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario7" name="second_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario7" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario7" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario7" name="tenth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario7" name="third_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario10" name="eigth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario10" name="fifth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario10" name="first_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario10" name="forth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario10" name="ninth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario10" name="second_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario10" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario10" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario10" name="tenth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario10" name="third_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario1" name="seventh_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario1" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario1" name="eigth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario1" name="fifth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario1" name="ninth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario1" name="tenth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario1" name="first_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario1" name="second_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario1" name="third_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario1" name="forth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario2" name="eigth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario2" name="fifth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario2" name="first_testcase" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at LearnTestNG.TestSenario2.first_testcase(TestSenario2.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="LearnTestNG.TestSenario2" name="forth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario2" name="ninth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario2" name="second_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario2" name="seventh_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario2" name="sixth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario2" name="tenth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario2" name="third_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario3" name="eigth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="fifth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="first_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="forth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="ninth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="second_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="seventh_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario3" name="sixth_testcase" time="0.001"/>
  <testcase classname="LearnTestNG.TestSenario3" name="tenth_testcase" time="0.0"/>
  <testcase classname="LearnTestNG.TestSenario3" name="third_testcase" time="0.0"/>
</testsuite> <!-- Test -->
